### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by alann-maulana**
- [x] Fix bugs, a lot of enhancement
- [x] Completing library documentation
- [x] Migrate to null safety
- [x] Add subclassing `ParseObject` and `ParseUser`

### CODE REVIEW

**Comment by matskosan** [comment]
Do you have an ETA on when this pull request could be finished?

**Comment by alann-maulana** [comment]
> Do you have an ETA on when this pull request could be finished?

FYI, I'm using this "unfinished yet" library at my 3 big projects this year. Sometimes, I do a lot of update, redesign, breaking changes etc. I'm hoping for the next month (of the next year) It will be stable enough and I can releasing it at pub server 😅

**Comment by matskosan** [comment]
Thank you for your work! I've forked the repo. Maybe I can contribute in some way in the future.

**Comment by alann-maulana** [comment]
> Thank you for your work! I've forked the repo. Maybe I can contribute in some way in the future.

Yeah great @matskosan , it would be fab 👍

**Pull request merged**
